/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinaria;

import dao.DAOHistorialClinico;
import dao.DAOPago;
import entidades.DetallePago;
import entidades.HistorialClinico;
import entidades.Pago;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Goku
 */
public class JFPago extends javax.swing.JFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    private List<DetallePago> detalles = new ArrayList<>();
    private List<HistorialClinico> historias;
    private HistorialClinico historia;
    
    public JFPago() {
        this.insertarColumnas();
        initComponents();
        this.txtIGV.setEditable(false);
        this.txtTotal.setEditable(false);
        this.txtPropietario.setEditable(false);
        this.dchFecha.setDate(Date.valueOf(LocalDate.now()));
        this.dchFecha.setEnabled(false);
        this.setLocationRelativeTo(null);
        
    }

    private void insertarColumnas(){
        this.modelo.addColumn("Servicio");
        this.modelo.addColumn("Costo");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panPago = new javax.swing.JPanel();
        dchFecha = new com.toedter.calendar.JDateChooser();
        lblFecha = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        cboDocumento = new javax.swing.JComboBox<>();
        lblBuscarPaciente = new javax.swing.JLabel();
        txtBuscarPaciente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        lblPaciente = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        panDetalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtIGV = new javax.swing.JTextField();
        lblIGV = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        Total = new javax.swing.JLabel();
        chkVigencia = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/market.png"))); // NOI18N
        jLabel1.setText("PAGOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panPago.setBackground(new java.awt.Color(0, 153, 102));

        dchFecha.setDateFormatString("dd-MM-yyyy");

        lblFecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblFecha.setText("Fecha");

        lblDocumento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblDocumento.setText("Documento");

        cboDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo de documento", "Boleta", "Factura" }));
        cboDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDocumentoActionPerformed(evt);
            }
        });

        lblBuscarPaciente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblBuscarPaciente.setText("Buscar Paciente");

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        lblPaciente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblPaciente.setText("Propietario");

        javax.swing.GroupLayout panPagoLayout = new javax.swing.GroupLayout(panPago);
        panPago.setLayout(panPagoLayout);
        panPagoLayout.setHorizontalGroup(
            panPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPagoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dchFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panPagoLayout.createSequentialGroup()
                        .addGroup(panPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBuscarPaciente)
                            .addComponent(lblPaciente)
                            .addComponent(lblDocumento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panPagoLayout.createSequentialGroup()
                                .addComponent(txtBuscarPaciente)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarCliente))
                            .addGroup(panPagoLayout.createSequentialGroup()
                                .addGroup(panPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panPagoLayout.setVerticalGroup(
            panPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarPaciente)
                    .addComponent(txtBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(panPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPagoLayout.createSequentialGroup()
                        .addGroup(panPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPaciente)
                            .addComponent(txtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocumento)
                            .addComponent(cboDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(lblFecha))
                    .addComponent(dchFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        panDetalle.setBackground(new java.awt.Color(153, 255, 153));

        tblDetalle.setModel(this.modelo);
        jScrollPane1.setViewportView(tblDetalle);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtIGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIGVActionPerformed(evt);
            }
        });

        lblIGV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblIGV.setForeground(new java.awt.Color(0, 0, 0));
        lblIGV.setText("IGV");

        Total.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Total.setForeground(new java.awt.Color(0, 0, 0));
        Total.setText("Total a pagar");

        chkVigencia.setText("Vigencia");

        javax.swing.GroupLayout panDetalleLayout = new javax.swing.GroupLayout(panDetalle);
        panDetalle.setLayout(panDetalleLayout);
        panDetalleLayout.setHorizontalGroup(
            panDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDetalleLayout.createSequentialGroup()
                        .addGroup(panDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkVigencia)
                            .addGroup(panDetalleLayout.createSequentialGroup()
                                .addComponent(lblIGV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(224, Short.MAX_VALUE))
                    .addGroup(panDetalleLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(panDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );
        panDetalleLayout.setVerticalGroup(
            panDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panDetalleLayout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIGV)
                    .addComponent(Total)
                    .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkVigencia)
                .addContainerGap())
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Registrar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panDetalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(panDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        JDDetallePago ventana = new JDDetallePago(this, true);
        DetallePago det;
        
        det = ventana.agregar();
        ventana.dispose();
        if (det != null) {
            this.detalles.add(det);
            this.modelo.addRow(new Object[]{
                det.getServicio().getNombre(),
                det.getPrecio()
            });
            
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private Double getIGV(){
        
        double suma = 0;
        for (DetallePago detalle : detalles) {
            suma = suma + (detalle.getPrecio()*0.18);
        }
        
        return suma;
    }
    private Double getTotal(){
        
        double total = 0;
        for (DetallePago detalle : detalles) {
            
            total = total + detalle.getPrecio();
        }
        
        return total;
    }
    
    private Double operacionTotal(){
        return this.getIGV() + getTotal();
    }
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        DAOPago dao = new DAOPago();
        Pago pago;
        
        if (this.validarDatos() == true) {
            pago = new Pago();
            
            pago.setFecha(this.dchFecha.getDate());
           
            pago.setHistotial(this.historia);
            /*pago.setHistotial(this.historias.get(
                this.cboPropietario.getSelectedIndex()));*/
            pago.setTipoPago(this.cboDocumento.getSelectedItem().toString()
                .substring(0, 1));
            if (this.cboDocumento.getSelectedIndex() == 1) {
                pago.setIGV(0.00);
                pago.setTotal(this.getTotal());
            }else if (this.cboDocumento.getSelectedIndex() == 2) {
                pago.setIGV(this.getIGV());
                pago.setTotal(this.operacionTotal());
            }else{
                JOptionPane.showMessageDialog(this, "Seleccione el tipo de documento");
            }
            
            pago.setVigencia(this.chkVigencia.isSelected());
            pago.setDetalle(this.detalles);
            
            dao = new DAOPago();
            try {
                dao.registrar(pago);
                JOptionPane.showMessageDialog(this, "!Venta realizada con Exito¡");
                this.limpiarControles();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }finally{
                pago = null;
                dao = null;
                this.historia = null;
            }
            
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void limpiarControles(){
        this.txtBuscarPaciente.setText("");
        this.txtPropietario.setText("");
        this.cboDocumento.setSelectedIndex(-1);
        this.tblDetalle.removeAll();
        this.modelo.setRowCount(0);
    }
    
    private void cboDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDocumentoActionPerformed
        int pos = this.cboDocumento.getSelectedIndex();

        if (pos == 1) {
            this.txtIGV.setText("S/."+0.00);
            this.txtTotal.setText("S/."+String.format("%.2f", this.getTotal()));
        }else if(pos == 2){
            this.txtIGV.setText("S/."+String.format("%.2f", this.getIGV()));
            this.txtTotal.setText("S/."+this.operacionTotal());
        }else{    
            this.txtIGV.setText("S/."+0.00);
            this.txtTotal.setText("S/."+0.00);
        }
    }//GEN-LAST:event_cboDocumentoActionPerformed

    private void txtIGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIGVActionPerformed
        
    }//GEN-LAST:event_txtIGVActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int pos = this.tblDetalle.getSelectedRow();
        
        if (pos > -1) {
            this.modelo.removeRow(pos);
            this.detalles.remove(pos);
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un detalle");
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        DAOHistorialClinico dao = new DAOHistorialClinico();
        int i = 0;
        if (this.txtBuscarPaciente.getText().length() > 0) {
            try {
            this.historias = dao.listarPropietario(this.txtBuscarPaciente.getText());
            for (HistorialClinico his : this.historias) {
                this.txtPropietario.setText(his.getNombrePropietario());
                
                this.historia = his;
                
            }
            //this.activarControles(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }finally{
                dao = null;
            }
        }
        
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    /*
    private void llenarTabla(){
        this.modelo.setRowCount(0);
        for (Vacuna vacuna : this.vacunas) {
            this.modelo.addRow(new Object[]{
                vacuna.getNobrePaciente(),
                vacuna.getProducto(),
                vacuna.getNombreFecha(),
                vacuna.getNombreRefuerzo(),
                (vacuna.isEstado()==true?"Valido":"Nulo"),
            });
        }
    }
    */
    
    private boolean validarDatos(){
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Total;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cboDocumento;
    private javax.swing.JCheckBox chkVigencia;
    private com.toedter.calendar.JDateChooser dchFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarPaciente;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIGV;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JPanel panDetalle;
    private javax.swing.JPanel panPago;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtBuscarPaciente;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
/*
  private void activarControles(boolean estado){
      this.lblBuscarPaciente.setEnabled(estado);
      this.txtBuscarPaciente.setEnabled(estado);
      this.lblPaciente.setEnabled(estado);
      this.txtPropietario.setEnabled(estado);
      this.btnBuscarCliente.setEnabled(estado);
      
      this.lblPropietario.setEnabled(!estado);
      this.cboPropietario.setEnabled(!estado);
      
      if (estado == true) {
          this.txtBuscarPaciente.requestFocusInWindow();
      }else{
          this.cboPropietario.requestFocusInWindow();
      }
  }
  */
  
  /*
  private void llenarCombo(DefaultComboBoxModel modelo) {
    for (HistorialClinico his : this.historia) {
      modelo.addElement(his.getNombrePropietario());
    }
  }*/
  /*
  private ComboBoxModel cargarHistorias() {
    
    DefaultComboBoxModel modelo = new DefaultComboBoxModel<>();

    try {
      this.historias = dao.listarPropietario(
              this.txtBuscarCliente.getText());
      this.llenarCombo(modelo);
    } catch (Exception e) {
      JOptionPane.showMessageDialog(this, "No se encontro ningun propietario " + e.getMessage());
    } 
    return modelo;
  }

  
  private void llenarCombo(DefaultComboBoxModel modelo) {
    for (HistorialClinico his : this.historias) {
      modelo.addElement(his.getPaciente());
    }
  }
    */
    
}
