/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinaria;

import dao.DAOHistorialClinico;
import entidades.HistorialClinico;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Goku
 */
public class JFPrincipal extends javax.swing.JFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    private List<HistorialClinico> historias;
    
    public JFPrincipal() {
        this.insertarColumnas();
        this.setResizable(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void insertarColumnas(){
        this.modelo.addColumn("ID de Historia");
        this.modelo.addColumn("Propietario");
        this.modelo.addColumn("Paciente");
        this.modelo.addColumn("Fecha de Registro");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPropietario = new rsbuttom.RSButtonMetro();
        btnPaciente = new rsbuttom.RSButtonMetro();
        btnHistorial = new rsbuttom.RSButtonMetro();
        btnVacunas = new rsbuttom.RSButtonMetro();
        btnConsultas = new rsbuttom.RSButtonMetro();
        btnVenta = new rsbuttom.RSButtonMetro();
        btnUsuarios = new rsbuttom.RSButtonMetro();
        btnServicios = new rsbuttom.RSButtonMetro();
        btnAñadirMedico = new rsbuttom.RSButtonMetro();
        btnConsultarVentas = new rsbuttom.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblPaciente = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuDatos = new javax.swing.JMenu();
        mnuPropietario = new javax.swing.JMenuItem();
        mnuPaciente = new javax.swing.JMenuItem();
        mnuHistorial = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenuItem();
        mnuVacuna = new javax.swing.JMenuItem();
        mnuPagos = new javax.swing.JMenuItem();
        mnuRegistarUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        btnPropietario.setBackground(new java.awt.Color(204, 204, 204));
        btnPropietario.setForeground(new java.awt.Color(0, 0, 0));
        btnPropietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/AÑADIR BOTn.png"))); // NOI18N
        btnPropietario.setText("PROPIETARIO");
        btnPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPropietarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnPropietario);

        btnPaciente.setBackground(new java.awt.Color(204, 204, 204));
        btnPaciente.setForeground(new java.awt.Color(0, 0, 0));
        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/EXPEDIENTE.png"))); // NOI18N
        btnPaciente.setText("PACIENTE");
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnPaciente);

        btnHistorial.setBackground(new java.awt.Color(204, 204, 204));
        btnHistorial.setForeground(new java.awt.Color(0, 0, 0));
        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/CONSULTA.png"))); // NOI18N
        btnHistorial.setText("HISTORIAL CLINICO");
        btnHistorial.setPreferredSize(new java.awt.Dimension(180, 35));
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistorial);

        btnVacunas.setBackground(new java.awt.Color(204, 204, 204));
        btnVacunas.setForeground(new java.awt.Color(0, 0, 0));
        btnVacunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/VACUNA.png"))); // NOI18N
        btnVacunas.setText("VACUNAS");
        btnVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacunasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVacunas);

        btnConsultas.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultas.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/CONSULTAPACIENTE1.png"))); // NOI18N
        btnConsultas.setText("CONSULTAS");
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultas);

        btnVenta.setBackground(new java.awt.Color(204, 204, 204));
        btnVenta.setForeground(new java.awt.Color(0, 0, 0));
        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/PAGO.png"))); // NOI18N
        btnVenta.setText("VENTA");
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVenta);

        btnUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        btnUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/USUARIO.png"))); // NOI18N
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuarios);

        btnServicios.setBackground(new java.awt.Color(204, 204, 204));
        btnServicios.setForeground(new java.awt.Color(0, 0, 0));
        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/AÑADIR BOTn.png"))); // NOI18N
        btnServicios.setText("SERVICIOS");
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(btnServicios);

        btnAñadirMedico.setBackground(new java.awt.Color(204, 204, 204));
        btnAñadirMedico.setForeground(new java.awt.Color(0, 0, 0));
        btnAñadirMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/AÑADIR BOTn.png"))); // NOI18N
        btnAñadirMedico.setText("AÑADIR MEDICO");
        btnAñadirMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadirMedico);

        btnConsultarVentas.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultarVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/BUSCAR.png"))); // NOI18N
        btnConsultarVentas.setText("CONSULTAR VENTAS");
        btnConsultarVentas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnConsultarVentas.setMaximumSize(new java.awt.Dimension(180, 45));
        btnConsultarVentas.setPreferredSize(new java.awt.Dimension(180, 35));
        btnConsultarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarVentas);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 460));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VETERINARIA \"MIS 4 PATAS\"");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 20, 790, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/FONDO.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 110);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 790, 110));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/MENU CASA.png"))); // NOI18N
        jPanel3.add(jLabel3);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 110));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTable1.setModel(this.modelo);
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 760, 360));

        lblPaciente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblPaciente.setForeground(new java.awt.Color(0, 0, 0));
        lblPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/web.png"))); // NOI18N
        lblPaciente.setText("Paciente");
        jPanel4.add(lblPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 160, 70));
        jPanel4.add(txtPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 29, 400, 30));

        btnBuscar.setBackground(new java.awt.Color(51, 102, 255));
        btnBuscar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img/BUSCAR.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel4.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 160, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 790, 450));

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 255));
        jMenuBar1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        mnuDatos.setText(" VENTANAS");
        mnuDatos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mnuDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDatosActionPerformed(evt);
            }
        });

        mnuPropietario.setText("Propietario");
        mnuPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPropietarioActionPerformed(evt);
            }
        });
        mnuDatos.add(mnuPropietario);

        mnuPaciente.setText("Paciente");
        mnuPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPacienteActionPerformed(evt);
            }
        });
        mnuDatos.add(mnuPaciente);

        mnuHistorial.setText("Historial del Paciente");
        mnuHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHistorialActionPerformed(evt);
            }
        });
        mnuDatos.add(mnuHistorial);

        mnuConsulta.setText("Consultas");
        mnuConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaActionPerformed(evt);
            }
        });
        mnuDatos.add(mnuConsulta);

        mnuVacuna.setText("Vacunas");
        mnuVacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVacunaActionPerformed(evt);
            }
        });
        mnuDatos.add(mnuVacuna);

        mnuPagos.setText("Pagos");
        mnuDatos.add(mnuPagos);

        mnuRegistarUsuario.setText("Registrar Usuario");
        mnuRegistarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistarUsuarioActionPerformed(evt);
            }
        });
        mnuDatos.add(mnuRegistarUsuario);

        jMenuBar1.add(mnuDatos);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPropietarioActionPerformed
        JFPropietario frame = new JFPropietario();
        
        frame.setVisible(true);
    }//GEN-LAST:event_mnuPropietarioActionPerformed

    private void mnuPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPacienteActionPerformed
        JFExpediente_Paciente frame = new JFExpediente_Paciente();
        
        frame.setVisible(true);
    }//GEN-LAST:event_mnuPacienteActionPerformed

    private void mnuHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHistorialActionPerformed
        JFHistorial_Clinico frame = new JFHistorial_Clinico();
        
        frame.setVisible(true);
    }//GEN-LAST:event_mnuHistorialActionPerformed

    private void mnuConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaActionPerformed
        
        JFConsulta frame = new JFConsulta();
        
        frame.setVisible(true);
    }//GEN-LAST:event_mnuConsultaActionPerformed

    private void mnuVacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVacunaActionPerformed
        JFVacunas frame = new JFVacunas();
        frame.setVisible(true);
    }//GEN-LAST:event_mnuVacunaActionPerformed

    private void mnuDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDatosActionPerformed
        JFPago frame = new JFPago();
        frame.setVisible(true);
    }//GEN-LAST:event_mnuDatosActionPerformed

    private void mnuRegistarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistarUsuarioActionPerformed
        JFRegistroUsuarios frame = new JFRegistroUsuarios();
        frame.setVisible(true);
                
    }//GEN-LAST:event_mnuRegistarUsuarioActionPerformed

    private void btnPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPropietarioActionPerformed
        JFPropietario ventana = new JFPropietario();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnPropietarioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DAOHistorialClinico dao = new DAOHistorialClinico();
        
        try {
            this.historias = dao.listarPropietario(this.txtPaciente.getText());
            this.llenarTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }finally{
            dao = null;
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        JFExpediente_Paciente ventana = new JFExpediente_Paciente();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        JFHistorial_Clinico ventana = new JFHistorial_Clinico();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacunasActionPerformed
        JFVacunas ventana = new JFVacunas();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnVacunasActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        JFConsulta ventana = new JFConsulta();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        JFPago ventana = new JFPago();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        JFRegistroUsuarios ventana = new JFRegistroUsuarios();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        JFServicio ventana = new JFServicio();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnAñadirMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirMedicoActionPerformed
        JFMedico ventana = new JFMedico();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnAñadirMedicoActionPerformed

    private void btnConsultarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVentasActionPerformed
        JFConsultasVentas ventana = new JFConsultasVentas();
        
        ventana.setVisible(true);
    }//GEN-LAST:event_btnConsultarVentasActionPerformed

    private void llenarTabla(){
        this.modelo.setRowCount(0);
        if (this.historias != null) {
            for (HistorialClinico historia : this.historias) {
                this.modelo.addRow(new Object[]{
                    historia.getCodigo(),
                    historia.getNombrePropietario(),
                    historia.getNombrePaciente(),
                    historia.getFechaRegistro(),
                    
                });
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnAñadirMedico;
    private javax.swing.JButton btnBuscar;
    private rsbuttom.RSButtonMetro btnConsultarVentas;
    private rsbuttom.RSButtonMetro btnConsultas;
    private rsbuttom.RSButtonMetro btnHistorial;
    private rsbuttom.RSButtonMetro btnPaciente;
    private rsbuttom.RSButtonMetro btnPropietario;
    private rsbuttom.RSButtonMetro btnServicios;
    private rsbuttom.RSButtonMetro btnUsuarios;
    private rsbuttom.RSButtonMetro btnVacunas;
    private rsbuttom.RSButtonMetro btnVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JMenuItem mnuConsulta;
    private javax.swing.JMenu mnuDatos;
    private javax.swing.JMenuItem mnuHistorial;
    private javax.swing.JMenuItem mnuPaciente;
    private javax.swing.JMenuItem mnuPagos;
    private javax.swing.JMenuItem mnuPropietario;
    private javax.swing.JMenuItem mnuRegistarUsuario;
    private javax.swing.JMenuItem mnuVacuna;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
